Added Project Structure feature and a ProjectPath Variable
CameronHerwig/taskt pull request #13
Opened 2020-05-21 12:36 UTC by fodfran

**Project Structure**

Features: 

- User will be prompted to either create or open a project at startup.
- An "Add Project" button has also been added to the taskt UI. 
- A new project will produce a Main.xml and project.json. 
- The project.json will include a "ProjectName", "Main", and "ScriptPaths": scripts listed by their relative paths to the project directory. 
- Attempting to close the project form will close taskt unless a project is already open.
- When creating a project, the project form will check for valid project names and locations, and whether the project already exists.
- When opening a project, the project form will check whether the file that's been selected is a "Main.xml"
- Attempting to open a project without a project.json will reload the project form. 
- New sub-scripts may be saved within the project directory or any of its sub-directories.
- Any attempt to open or save a script outside of the project directory will be caught and prevented by taskt.
- Sub-scripts may be moved within the project directory, and the project.json will update the next time the project is opened or any scripts are saved. 

Constraints/Future To-Do: 

- The Project directory may be moved, but it cannot be renamed.
- Main.xml and project.json cannot be moved or renamed. 

**ProjectPath Variable**

- A ProjectPath variable containing the project's path will be added to a script's variable list whenever a script is created or opened within a project.
- This variable will updated accordingly if the project directory is moved.

2020-05-22 18:18 UTC, melugi requested changes
I've left comments on the things which I think need to be changed, feel free to ask any questions or leave a comment if you think my suggestions are misled. But it looks good and like it functions, awesome work!

2020-05-22 18:18 UTC, melugi commented on taskt/Core/Project.cs
> +using taskt.Core.Script;
I don't see some of these being used (`System.Threading.Tasks` and `System.Linq` at a quick glance). Can you clean these?

2020-05-22 18:18 UTC, melugi commented on taskt/Core/Project.cs
> +        public List<string> ScriptPaths { get; set; }
We should try to privatize data fields like these wherever possible so we can start to get a sense of [data encapsulation](https://en.wikipedia.org/wiki/Encapsulation_(computer_programming)) within the project design. If an outside scope needs the value then we can access it through public getter/setter methods. This allows us to hide any logic related to the getting/setting inside the object and removes the responsibility from the calling scope, which wouldn't be possible if we were just accessing the property publicly. Keep in mind if necessary having public properties is fine, we should just make an active effort to avoid them.

Also as we move away from having the majority of an object's properties exposed to the public we'll start to get some sense of [uniform access](https://martinfowler.com/bliki/UniformAccessPrinciple.html) which will help alleviate the issues we see now such as the confusion over how to properly add variables to the variable list from a command (i.e shoould I use ExtensionMethods.StoreInUserVariable, AutomationEngineInstance.AddVariable, or AutomationEngineInstance.VariableList?)

2020-05-22 18:18 UTC, melugi commented on taskt/Core/Project.cs
> +        public static Project CreateProject(string projectPath, string projectName, string mainScriptPath, Script.Script mainScript)
Can you put this in the constructor? We can pass in the projectPath and projectName into the constructor and have a new project object made.

2020-05-22 18:18 UTC, melugi commented on taskt/UI/Forms/Supplement Forms/frmProjectBuilder.cs
> +                }
The second check to `!isInvalidProjectName` isn't necessary, in the first if-statement we're doing a positive check and if that bool is true then we throw an exception which means if we ever reach the second if-statement that bool has to be false.

2020-05-22 18:18 UTC, melugi commented on taskt/UI/Forms/Supplement Forms/frmProjectBuilder.cs
> +                }
Also if using if-statements without curly braces, can you add an empty line between unrelated if statements?

2020-05-22 18:18 UTC, melugi commented on taskt/UI/Forms/frmScriptBuilder.cs
> +        private string scriptProjectPath { get; set; }
Lets put this above the constructor, as with all fields. If you see fields under the constructor please move them up so we have a clear place to find them.

2020-05-22 18:29 UTC, fodfran commented on taskt/Core/Project.cs
> +using taskt.Core.Script;
done

2020-05-22 18:31 UTC, fodfran commented on taskt/UI/Forms/Supplement Forms/frmProjectBuilder.cs
> +                }
You're right. I forgot to get rid of that. Done

2020-05-22 18:37 UTC, fodfran commented on taskt/UI/Forms/frmScriptBuilder.cs
> +        private string scriptProjectPath { get; set; }
done

2020-05-22 18:49 UTC, fodfran commented on taskt/Core/Project.cs
> +        public static Project CreateProject(string projectPath, string projectName, string mainScriptPath, Script.Script mainScript)
done

2020-05-22 20:30 UTC, fodfran commented on taskt/Core/Project.cs
> +        public List<string> ScriptPaths { get; set; }
Thanks for the advice. I cleaned up as much as possible and made all the Project.cs properties private, but for frmProjectBuilder, I've only changed the setters to private. I don't know how I feel about making 6 getter methods. What do you think?

2020-05-27 22:02 UTC, melugi commented on taskt/Core/Project.cs
> +        public List<string> ScriptPaths { get; set; }
That's fine, there's not an issue with having *some* stuff public but it's just an issue when the default visibility is public.

2020-05-27 22:03 UTC, melugi commented
Looks good to me 👍

2020-05-27 22:03 UTC, melugi approved these changes

2020-05-28 02:12 UTC, CameronHerwig approved these changes
Looks good to me with the requested changes!

2020-05-28 02:12 UTC, merged