Cleaned Up taskt.Core.Automation.ApplicationSettings.cs File
CameronHerwig/taskt pull request #21
Opened 2020-06-01 21:06 UTC by fodfran

Cleaned up taskt.Core.Automation.ApplicationSettings and split classes into their own files.

2020-06-02 14:02 UTC, CameronHerwig submitted a review, later dismissed

2020-06-02 17:13 UTC, ob-ab submitted a review, later dismissed
Looks fine

2020-06-02 21:15 UTC, melugi commented on taskt/Core/Settings/EngineSettings.cs
> +        public System.Windows.Forms.Keys CancellationKey { get; set; }
Can you shorten this reference?

2020-06-02 21:15 UTC, melugi commented on taskt/Core/Settings/EngineSettings.cs
> +            CancellationKey = System.Windows.Forms.Keys.Pause;
Shorten this reference as well.

2020-06-02 21:17 UTC, melugi requested changes
Looks good, there were two small changes that need to be made. Thanks!

2020-06-03 13:48 UTC, fodfran commented on taskt/Core/Settings/EngineSettings.cs
> +            CancellationKey = System.Windows.Forms.Keys.Pause;
done

2020-06-03 13:48 UTC, fodfran commented on taskt/Core/Settings/EngineSettings.cs
> +        public System.Windows.Forms.Keys CancellationKey { get; set; }
done

2020-06-03 14:33 UTC, melugi submitted a review, later dismissed

2020-06-03 15:53 UTC, melugi submitted a review, later dismissed

2020-06-03 17:40 UTC, Ali-Basharat commented on taskt/Core/Settings/WhiteListIPSettings.cs
> +        public WhiteListIPSettings(string s)
Can you please change this parameter name `string s` to a meaningful variable name.

2020-06-03 17:44 UTC, ob-ab reviewed
Please make a small change of renaming Parameter name to a meaningful variable name.
Everything else looks good to me.

2020-06-03 17:51 UTC, CameronHerwig commented on taskt/Core/Settings/ServerSettings.cs
> +            HTTPServerURL = "https://localhost:44377/";
Long term we should move this into an app config. Short term this is fine.

2020-06-03 17:53 UTC, CameronHerwig approved these changes

2020-06-03 17:53 UTC, ob-ab approved these changes
Looks fine.

2020-06-03 17:53 UTC, merged