Cleaned Up If Commands
CameronHerwig/taskt pull request #61
Opened 2020-06-22 14:52 UTC by Ali-Basharat

Cleaned up following files:
- BeginIfCommand.cs
- BeginMutliIfCommand.cs
- ElseCommand.cs
- EndIfCommand.cs

2020-06-22 18:54 UTC, CameronHerwig requested changes

2020-06-22 18:54 UTC, CameronHerwig commented on taskt/Core/Automation/Commands/If Commands/BeginMutliIfCommand.cs
> +    [Description("This command evaluates a group of combined logical statements to determine if the combined result of the statements is 'true' or 'false' and subsequently performs action(s) based on
Change to "based on the result."

2020-06-22 19:25 UTC, Ali-Basharat commented on taskt/Core/Automation/Commands/If Commands/BeginMutliIfCommand.cs
> +    [Description("This command evaluates a group of combined logical statements to determine if the combined result of the statements is 'true' or 'false' and subsequently performs action(s) based on
done

2020-06-22 19:28 UTC, CameronHerwig submitted a review, later dismissed

2020-06-23 03:00 UTC, openbots-ff requested changes

2020-06-23 03:00 UTC, openbots-ff commented on taskt/Core/Automation/Commands/If Commands/BeginIfCommand.cs
> +        [PropertyUISelectionOption("Value")]
```suggestion
        [PropertyUISelectionOption("Value Compare")]
```

2020-06-23 03:00 UTC, openbots-ff commented on taskt/Core/Automation/Commands/If Commands/BeginIfCommand.cs
>                  case "Value":
```suggestion
                case "Value Compare":
```

2020-06-23 13:38 UTC, CameronHerwig approved these changes

2020-06-23 16:15 UTC, openbots-ff approved these changes

2020-06-24 15:12 UTC, merged