Json serialization merge resolution
CameronHerwig/taskt pull request #74
Opened 2020-07-07 14:54 UTC by melugi

Resolves bugs introduced in the merge of the json serialization/deserialization. This includes:
* Removing redundant frmScriptBuilder
* Replacing checks for .xml within script file names with checks for .json

2020-07-07 16:54 UTC, openbots-ff requested changes

2020-07-07 16:54 UTC, fodfran commented on taskt/UI/Forms/ScriptBuilder Forms/frmScriptBuilderTabControl.cs
>                  result = MessageBox.Show($"Would you like to save {tab.Name}.xml before closing this tab?",
```suggestion
                result = MessageBox.Show($"Would you like to save {tab.Name}.json before closing this tab?",
```

2020-07-08 14:20 UTC, openbots-ff approved these changes

2020-07-08 15:18 UTC, CameronHerwig approved these changes

2020-07-08 15:18 UTC, merged