Logging enhancement
CameronHerwig/taskt pull request #91
Opened 2020-08-05 18:43 UTC by fodfran

- Responsibility of Logger instantiation has been moved out of the AutomationEngineInstance and into Studio or wherever necessary.
- User can now set the Engine Logger in Studio Settings to File, HTTP, or SignalR and set their respective parameters. 
- User can explicitly write logs using the Log Message Command.
- Necessary modifications to the Documentation Generation have been added to account for the changes made in the command cleanup.

2020-08-06 10:12 UTC, Ali-Basharat commented on taskt.Studio/Commands/Engine Commands/LogMessageCommand.cs
> +        [PropertyUIHelper(UIAdditionalHelperType.ShowVariableHelper)]
I think we do not provide a VariableHelper for a dropdown.

2020-08-06 10:16 UTC, Ali-Basharat commented on taskt.Studio/Commands/Engine Commands/LogMessageCommand.cs
> +        public string v_LogType { get; set; }
```suggestion
        [Remarks("")]
        public string v_LogType { get; set; }
```

2020-08-06 10:18 UTC, ob-ab requested changes
Please make a suggested change as I remember that we do not provide a VariableHelper for a Dropdown.

2020-08-06 18:34 UTC, CameronHerwig submitted a review, later dismissed

2020-08-07 14:38 UTC, ob-ab approved these changes
Please make a suggested change.

2020-08-07 16:10 UTC, CameronHerwig approved these changes

2020-08-07 16:10 UTC, merged